import{a as L,S as w,i as s}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const b="https://pixabay.com/api/",v="51834666-cf153cf5c7da2b7bccbcade97";async function m(a,r=1,e=15){try{return(await L.get(b,{params:{key:v,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:e}})).data}catch(n){throw console.error("Ошибка при запросе к Pixabay:",n),n}}const f=document.querySelector(".gallery"),y=document.querySelector(".loader");let B=new w(".gallery a",{captionsData:"alt",captionDelay:250});function E(){f.innerHTML=""}function g(a){const r=a.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
          <p>👍 ${e.likes}</p>
          <p>👁️ ${e.views}</p>
          <p>💬 ${e.comments}</p>
          <p>⬇️ ${e.downloads}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",r),B.refresh()}function h(){y.classList.remove("hidden")}function c(){y.classList.add("hidden")}function S(){document.getElementById("loadMoreBtn").classList.remove("hidden")}function p(){document.getElementById("loadMoreBtn").classList.add("hidden")}const u=document.querySelector("#searchForm"),M=document.getElementById("loadMoreBtn");document.querySelector(".gallery");let i=1,d="";u.addEventListener("submit",async a=>{a.preventDefault();const r=u.elements["search-text"].value.trim();if(!r){s.error({title:"Error",message:"Please enter a search term!"});return}d=r,i=1,E(),h();try{const e=await m(r,i,15);if(e.hits.length===0){s.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(e.hits),e.hits.length>0&&i*15<e.totalHits?S():p()}catch{s.error({title:"Error",message:"Something went wrong. Try again!"})}finally{c()}});async function P(){if(d){h();try{const a=await m(d,i+1,15);if(a.hits.length===0){s.warning({title:"No more images",message:"There are no more images to load."}),c(),p();return}g(a.hits),i++,c()}catch{s.error({title:"Error",message:"Something went wrong. Try again!"}),c()}}}M.addEventListener("click",P);
//# sourceMappingURL=index.js.map
