import{a as w,S as v,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=e(t);fetch(t.href,n)}})();const E="https://pixabay.com/api/",b="51834666-cf153cf5c7da2b7bccbcade97";async function h(o,r=1,e=15){try{return(await w.get(E,{params:{key:b,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:e}})).data}catch(s){throw console.error("Ошибка при запросе к Pixabay:",s),s}}const m=document.querySelector(".gallery"),y=document.querySelector(".loader");let B=new v(".gallery a",{captionsData:"alt",captionDelay:250});function S(){m.innerHTML=""}function g(o){const r=o.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
          <p>👍 ${e.likes}</p>
          <p>👁️ ${e.views}</p>
          <p>💬 ${e.comments}</p>
          <p>⬇️ ${e.downloads}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",r),B.refresh()}function p(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}function L(){document.getElementById("loadMoreBtn").classList.remove("hidden")}function c(){document.getElementById("loadMoreBtn").classList.add("hidden")}const f=document.querySelector("#searchForm"),M=document.getElementById("loadMoreBtn"),P=document.querySelector(".gallery");let i=1,u="";f.addEventListener("submit",async o=>{o.preventDefault();const r=f.elements["search-text"].value.trim();if(!r){a.error({title:"Error",message:"Please enter a search term!"});return}u=r,i=1,S(),c(),p();try{const e=await h(r,i,15);if(e.hits.length===0){a.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(e.hits),i*15<e.totalHits?L():a.info({title:"End",message:"You've reached the end of the results."})}catch{a.error({title:"Error",message:"Something went wrong. Try again!"})}finally{d()}});async function q(){if(u){c(),p();try{i++;const o=await h(u,i,15);if(o.hits.length===0){a.info({title:"End",message:"You've reached the end of the results."}),d(),c();return}g(o.hits);const{height:r}=P.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),i*15<o.totalHits?L():(a.info({title:"End",message:"You've reached the end of the results."}),c())}catch{a.error({title:"Error",message:"Something went wrong. Try again!"})}finally{d()}}}M.addEventListener("click",q);
//# sourceMappingURL=index.js.map
